<a href="https://colab.research.google.com/github/4ldooo/pm-turi2-preprocessing-AhmadAliMurtadlo/blob/main/PM_P4_AhmadAliMurtadlo_2488010056.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Dataset karyawan (sengaja mengandung masalah kualitas)
data = {
    'usia'      : [25, 32, np.nan, 45, 28, 51, 38, np.nan, 29, 41],
    'pendapatan': [4_000_000, 7_500_000, 5_200_000, 12_000_000, 4_800_000,
                   15_000_000, 8_100_000, 6_300_000, np.nan, 9_900_000],
    'pendidikan': ['SMA','S1','SMA','S2','SMA','S2','S1','S1','SMA','S2'],  # ordinal
    'kota'      : ['Bandung','Jakarta','Bandung','Surabaya','Jakarta',
                   'Surabaya','Jakarta','Bandung','Bandung','Jakarta'],    # nominal
    'membeli'   : ['Tidak','Ya','Tidak','Ya','Tidak','Ya','Ya','Tidak','Tidak','Ya']  # target
}
df = pd.DataFrame(data)
df

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2   NaN   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7   NaN   6300000.0         S1   Bandung   Tidak
8  29.0         NaN        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

In [ ]:
df.isna().sum()

usia          0
pendapatan    0
pendidikan    0
kota          0
membeli       0
dtype: int64

In [ ]:
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())
df

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2  35.0   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7  35.0   6300000.0         S1   Bandung   Tidak
8  29.0   7500000.0        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

In [ ]:
X = df.drop(columns=['membeli'])
y = df['membeli']
X

   usia  pendapatan pendidikan      kota
0  25.0   4000000.0        SMA   Bandung
1  32.0   7500000.0         S1   Jakarta
2  35.0   5200000.0        SMA   Bandung
3  45.0  12000000.0         S2  Surabaya
4  28.0   4800000.0        SMA   Jakarta
5  51.0  15000000.0         S2  Surabaya
6  38.0   8100000.0         S1   Jakarta
7  35.0   6300000.0         S1   Bandung
8  29.0   7500000.0        SMA   Bandung
9  41.0   9900000.0         S2   Jakarta

In [ ]:
X['pendidikan'] = X['pendidikan'].map({'SMA':0,'S1':1,'S2':2})
X = pd.get_dummies(X, columns=['kota'], dtype=int)
y = y.map({'Tidak':0,'Ya':1})
X

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  25.0   4000000.0           0             1             0              0
1  32.0   7500000.0           1             0             1              0
2  35.0   5200000.0           0             1             0              0
3  45.0  12000000.0           2             0             0              1
4  28.0   4800000.0           0             0             1              0
5  51.0  15000000.0           2             0             0              1
6  38.0   8100000.0           1             0             1              0
7  35.0   6300000.0           1             1             0              0
8  29.0   7500000.0           0             1             0              0
9  41.0   9900000.0           2             0             1              0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)
print("X_train:", X_train.shape, "| X_test:", X_test.shape)

X_train: (7, 6) | X_test: (3, 6)

In [ ]:
from sklearn.preprocessing import StandardScaler
num = ['usia','pendapatan','pendidikan']
sc = StandardScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num]  = sc.transform(X_test[num])  # cegah data leakage
X_train

       usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0 -1.588665   -1.169416   -1.028992             1             0              0
7 -0.044130   -0.325129    0.171499             1             0              0
2 -0.044130   -0.728919   -1.028992             1             0              0
9  0.882592    0.996363    1.371989             0             1              0
4 -1.125304   -0.875751   -1.028992             0             1              0
3  1.500406    1.767234    1.371989             0             0              1
6  0.419231    0.335617    0.171499             0             1              0

In [ ]:
print("Nilai hilang di X_train:", X_train.isna().sum().sum())
print("Nilai hilang di X_test :", X_test.isna().sum().sum())
print("Semua kolom numerik?", all(np.issubdtype(dt, np.number) for dt in X_train.dtypes))
print("\nMean kolom numerik X_train (harus ~0):")
print(X_train[num].mean().round(4))
print("\nStd kolom numerik X_train (harus ~1):")
print(X_train[num].std(ddof=0).round(4))

Nilai hilang di X_train: 0
Nilai hilang di X_test : 0
Semua kolom numerik? True

Mean kolom numerik X_train (harus ~0):
usia          0.0
pendapatan    0.0
pendidikan   -0.0
dtype: float64

Std kolom numerik X_train (harus ~1):
usia          1.0
pendapatan    1.0
pendidikan    1.0
dtype: float64

In [ ]:
df_raw = pd.DataFrame(data)  # data mentah lagi (belum diimputasi)

usia_mean = df_raw['usia'].mean()
usia_median = df_raw['usia'].median()
print(f"Mean usia   : {usia_mean:.4f}")
print(f"Median usia : {usia_median:.4f}")

df_mean = df_raw.copy()
df_mean['usia'] = df_mean['usia'].fillna(usia_mean)

df_median = df_raw.copy()
df_median['usia'] = df_median['usia'].fillna(usia_median)

perbandingan = pd.DataFrame({
    'usia_asli (NaN)': df_raw['usia'],
    'usia_isi_mean': df_mean['usia'],
    'usia_isi_median': df_median['usia']
})
perbandingan.loc[[2, 7]]

Mean usia   : 36.1250
Median usia : 35.0000

   usia_asli (NaN)  usia_isi_mean  usia_isi_median
2              NaN         36.125             35.0
7              NaN         36.125             35.0

In [ ]:
print("Statistik usia (versi MEAN):")
print(df_mean['usia'].describe().round(3))
print("\nStatistik usia (versi MEDIAN):")
print(df_median['usia'].describe().round(3))

Statistik usia (versi MEAN):
count    10.000
mean     36.125
std       8.061
min      25.000
25%      29.750
50%      36.125
75%      40.250
max      51.000
Name: usia, dtype: float64

Statistik usia (versi MEDIAN):
count    10.000
mean     35.900
std       8.075
min      25.000
25%      29.750
50%      35.000
75%      40.250
max      51.000
Name: usia, dtype: float64

In [ ]:
df3 = pd.DataFrame(data)
# Kolom kategorikal baru: status kepegawaian (nominal)
df3['status_kerja'] = ['Kontrak','Tetap','Kontrak','Tetap','Kontrak',
                        'Tetap','Tetap','Kontrak','Kontrak','Tetap']

df3['usia'] = df3['usia'].fillna(df3['usia'].median())
df3['pendapatan'] = df3['pendapatan'].fillna(df3['pendapatan'].median())

X3 = df3.drop(columns=['membeli'])
y3 = df3['membeli']
X3['pendidikan'] = X3['pendidikan'].map({'SMA':0,'S1':1,'S2':2})
X3 = pd.get_dummies(X3, columns=['kota','status_kerja'], dtype=int)
y3 = y3.map({'Tidak':0,'Ya':1})

print(f"Jumlah kolom fitur sebelumnya: 6")
print(f"Jumlah kolom fitur setelah tambah 'status_kerja': {X3.shape[1]}")

Jumlah kolom fitur sebelumnya: 6
Jumlah kolom fitur setelah tambah 'status_kerja': 8

## 4. Jelaskan mengapa `fit_transform` pada data latih tetapi hanya `transform` pada data uji

`fit_transform` melakukan dua hal sekaligus: **fit** (menghitung parameter statistik seperti mean & std untuk `StandardScaler`, atau min & max untuk `MinMaxScaler`) dan **transform** (menerapkan parameter tersebut ke data). Parameter ini **hanya boleh dihitung dari data latih**, karena:

- Data uji harus diperlakukan seolah-olah "belum pernah dilihat" oleh model, meniru kondisi dunia nyata saat model menerima data baru.
- Jika kita ikut menghitung mean/std/min/max dari data uji (misalnya dengan memanggil `fit_transform` lagi di data test), maka informasi dari data uji akan "bocor" ke proses training — ini disebut **data leakage**.
- Data leakage membuat evaluasi model menjadi bias (terlihat lebih baik dari performa sebenarnya), sehingga hasil di dunia nyata bisa mengecewakan.

Karena itu, urutan yang benar adalah: **split terlebih dahulu → fit scaler hanya di data train → transform data train dan data test memakai scaler yang sama.**

---
# E. Refleksi

**1. Mengapa urutan 'split dulu, baru scaling' penting?**

Karena jika scaling dilakukan sebelum split (fit pada seluruh dataset), statistik (mean, std, min, max) yang digunakan untuk scaling akan mengandung informasi dari data uji. Ini menyebabkan **data leakage**: model "mengintip" karakteristik data yang seharusnya belum ia lihat, sehingga evaluasi performa model menjadi tidak jujur/terlalu optimis. Dengan split dulu, scaler hanya belajar dari data latih, menjaga data uji benar-benar independen sebagai simulasi data baru.

**2. Kapan label encoding dan kapan one-hot encoding digunakan?**

- **Label encoding** (memetakan kategori ke angka urut, misal SMA=0, S1=1, S2=2) digunakan untuk data **ordinal**, yaitu kategori yang memiliki urutan/tingkatan yang bermakna. Contoh: tingkat pendidikan, karena S2 memang "lebih tinggi" dari S1 dan SMA.
- **One-hot encoding** (membuat kolom biner 0/1 untuk tiap kategori) digunakan untuk data **nominal**, yaitu kategori tanpa urutan yang bermakna. Contoh: kota (Bandung, Jakarta, Surabaya) — tidak ada kota yang "lebih besar" dari kota lain secara numerik, sehingga label encoding di sini justru akan menyesatkan model (model bisa salah menganggap ada hubungan ordinal padahal tidak ada).

**3. Apa perbedaan normalisasi dan standardisasi?**

- **Normalisasi** (contoh: `MinMaxScaler`) mengubah skala data ke rentang tertentu, biasanya [0, 1], dengan rumus `(x - min) / (max - min)`. Cocok digunakan saat distribusi data tidak diketahui normal, atau saat algoritma membutuhkan rentang nilai yang tetap (misalnya jaringan saraf/neural network, atau algoritma berbasis jarak seperti KNN).
- **Standardisasi** (contoh: `StandardScaler`) mengubah data agar memiliki rata-rata (mean) = 0 dan standar deviasi = 1, dengan rumus `(x - mean) / std`. Cocok digunakan saat data mendekati distribusi normal, atau saat algoritma mengasumsikan data terdistribusi normal (misalnya regresi linear, SVM, PCA).
- Perbedaan utama: normalisasi membatasi nilai ke rentang tertentu (sensitif terhadap outlier karena bergantung pada min/max), sedangkan standardisasi berpusat pada distribusi data (rata-rata & sebaran) dan tidak membatasi rentang nilai secara eksplisit.